# Generated by Django 2.0.13 on 2019-06-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='week')),
                ('future_week_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='future week price')),
                ('future_week_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='future week return')),
                ('future_month_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='future month price')),
                ('future_month_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='future month return')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prediction.WeeklyPrediction')),
            ],
        ),
    ]
