# Generated by Django 2.0.13 on 2019-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecommendation',
            name='rank',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='weeklyrecommendation',
            name='strategy',
            field=models.CharField(blank=True, max_length=80, verbose_name='strategy'),
        ),
    ]
