# Generated by Django 2.0.13 on 2019-06-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20190619_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecommendation',
            name='future_month_price',
        ),
        migrations.RemoveField(
            model_name='weeklyrecommendation',
            name='future_month_return',
        ),
        migrations.RemoveField(
            model_name='weeklyrecommendation',
            name='future_week_price',
        ),
        migrations.RemoveField(
            model_name='weeklyrecommendation',
            name='future_week_return',
        ),
    ]
