# Generated by Django 2.0.13 on 2019-06-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20190620_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyrecommendation',
            old_name='code',
            new_name='prediction',
        ),
    ]
