# Generated by Django 2.0.13 on 2019-06-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='asx_200',
            field=models.BooleanField(default=False),
        ),
    ]
