# Generated by Django 2.0.13 on 2019-06-23 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asx', '0004_company_daily_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 23, 3, 59, 32, 179128, tzinfo=utc), verbose_name='create at'),
            preserve_default=False,
        ),
    ]
